### ISSUE TITLE
Update for Nakama 2.x

### ISSUE THREAD

**Issue by novabyte** [nazgulsenpai/Nakama.Godot#1]
@nazgulsenpai This project looks great. I wanted to let you know I've created a new low level .NET client which you can use as the base for this project and Godot engine - https://github.com/heroiclabs/nakama-dotnet

Hope it helps and let me know if you have questions.

**Comment by nazgulsenpai** [comment]
I've started using it, as a matter of fact. In my own project I've started replacing chunks to the dotnet library. I'm almost certain the nakama-dotnet lib will eliminate the need for any Godot-specific implementation (for C# anyway). I'm going to look into creating a GDNative (C++) module or in plain GDScript Nakama librsry,  however, because I think our community would benefit greatly from your guys' work with Nakama. And congratulations on the 2.0 release. I'm still testing features but very exciting!!

**Comment by nazgulsenpai** [comment]
Thinking about it more, I will create an empty Godot Mono project with the nakama-dotnet library referenced and included (and the .net version target to 4.6.1) in this repo in a new 2.0 branch. I will get this done over the weekend.

**Comment by novabyte** [comment]
Nice one @nazgulsenpai. Let me know if I can help with any advice on how to configure the client, etc.

**Comment by nazgulsenpai** [comment]
After a very long delay, this has been updated/completed.

**Comment by novabyte** [comment]
Nice one @nazgulsenpai! :thumbsup:
